### ISSUE TITLE
Login process for users

### ISSUE THREAD

**Issue by Justinfan827** [rice-apps/RiceDeliveryUserFrontend#28]
### Current behavior:
- Authentication works, and user is able to login. 

### Desired behavior: There should be a single sign in button on the homepage. This leads to the authentication page. If the user is correctly authenticated, two possible scenarios:
1. User is new and has not registered in the app
    - In this case: bring user through onboard flow (add a screen for users to input their initial information). Then use this information to send a backend call to create the user
    - If backend call returns a user, it means user successfully created. Proceed to navigate to vendor selection screen
2. User is not new: navigate to vendor selection screen right away.

**Comment by amyhuyen98** [comment]
Completed on branch feature/28 on use frontend and on branch feature/userExistence on backend
