### ISSUE TITLE
Bug when logging in

### ISSUE THREAD

**Issue by Justinfan827** [rice-apps/RiceDeliveryUserFrontend#30]
When one of my friends tries to log in, authorization fails:

Console: ![Screen Shot 2019-02-26 at 10.35.46 PM.png](https://images.zenhubusercontent.com/5b9ab0f47dfd064d6bed87fb/18fd4807-cf8e-4d27-9e44-47911e3d0d77)

**Comment by amyhuyen98** [comment]
Completed as part of onboarding process

Ready to be merged (feature/28 on user frontend and feature/userExistence on backend)
